name: Gregcraft2
version: '${project.version}'
main: gregcraft2.gregcraft2.Gregcraft2
api-version: 1.20
commands:
  test:
    description: a test command, not useful for the game.
    usage: /test
  hub:
    description: Go to the hub world.
    usage: /hub
  join:
    description: join a world.
    usage: /join <world_name>